# Generated by Django 5.2 on 2026-06-21 16:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Полигон в системе координат WGS84 (EPSG:4326)', srid=4326)),
                ('address', models.CharField(help_text='Почтовый адрес здания', max_length=255)),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'ordering': ['address'],
            },
        ),
    ]
